version: "3"

services:

  webserver:
    image: alexandregv/camagru-webserver:latest
    build: ./webserver
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    networks:
      - default
#     - traefik_traefik
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${SSMTP_CONF-./config/ssmtp/ssmtp.conf}:/etc/ssmtp/ssmtp.conf
    labels:
      traefik.enable: false
      traefik.docker.network: "traefik_traefik"
      traefik.http.services.camagrugq.loadbalancer.server.port: "80"
      #HTTP
      traefik.http.routers.camagrugq.entrypoints: "http"
      traefik.http.routers.camagrugq.rule: "Host(`camagru.gq`)"
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.routers.camagrugq.middlewares: "redirect-https"
      # HTTPS
      traefik.http.routers.camagrugq-secure.entrypoints: "https"
      traefik.http.routers.camagrugq-secure.rule: "Host(`camagru.gq`)"
      traefik.http.routers.camagrugq-secure.tls: "true"
      # TLS
      traefik.http.routers.camagrugq-secure.tls.certresolver: "le-camagru"
      traefik.http.routers.camagrugq-secure.tls.domains[0].main: "camagru.gq"

  mysql:
    image: mysql:8.0
    user: "1000:1000"
    command: "--innodb_use_native_aio=0 --lower_case_table_names=1 --default-authentication-plugin=mysql_native_password"
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    networks:
      - default
    volumes:
      - "${DOCUMENT_ROOT-./www}/config/setup.sql:/docker-entrypoint-initdb.d/setup.sql:rw"
      - "${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:rw"
      - "${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      traefik.enable: false

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      #PMA_USER: ${MYSQL_USER}
      #PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
    networks:
      - default
#     - traefik_traefik
    volumes:
      - /sessions
#      - ${PMA_CONFIG-./config/phpmyadmin/config.user.inc.php}:/etc/phpmyadmin/config.user.inc.php
    labels:
      traefik.enable: false
      traefik.docker.network: "traefik_traefik"
      traefik.http.services.camagru-pma.loadbalancer.server.port: "80"
      #HTTP
      traefik.http.routers.camagrugq-pma.entrypoints: "http"
      traefik.http.routers.camagrugq-pma.rule: "Host(`pma.camagru.gq`)"
      traefik.http.middlewares.redirect-https.redirectscheme.scheme: "https"
      traefik.http.routers.camagrugq-pma.middlewares: "redirect-https"
      # HTTPS
      traefik.http.routers.camagrugq-pma-secure.entrypoints: "https"
      traefik.http.routers.camagrugq-pma-secure.rule: "Host(`pma.camagru.gq`)"
      traefik.http.routers.camagrugq-pma-secure.tls: "true"
      # TLS
      traefik.http.routers.camagrugq-pma-secure.tls.certresolver: "le-camagru"
      traefik.http.routers.camagrugq-pma-secure.tls.domains[0].main: "pma.camagru.gq"

#  maildev:
#    image: djfarrelly/maildev
#    ports:
#      - "1080:80"
#    networks:
#      - default
#    labels:
#      traefik.enable: false

# compass:
#   image: antonienko/compass-watch
#   command: watch --poll /var/www/html/public/assets
#   volumes:
#     - ${ASSETS_DIR-./www/public/assets}:/var/www/html/public/assets
#   labels:
#     traefik.enable: false

networks:
  default:
# traefik_traefik:
#   external: true
